name: Manual workflow

on: [workflow_dispatch]

jobs:
  start-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start MediaWiki and tests
        run: docker-compose -f docker-compose.yml -f docker-compose.actual.yml up
