name: Manual workflow

on: [workflow_dispatch]

jobs:
  start-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install
      - name: Start MediaWiki
        run: npm run up:mw -- -d
      - name: Start sorry-cypress director
        run: npm run up:director -- -d
      - name: Run Cypress tests
        run: npm run up:test2
      - name: Generate report
        run: npm run report
      - name: Save report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: mochawesome-report
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: cypress/results/**/*.xml
