name: Manual workflow

on: [workflow_dispatch]

jobs:
  start-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install
      - name: Start MediaWiki and run Cypress tests
        run: docker-compose -f docker-compose.yml -f docker-compose.actual.yml up --exit-code-from cypress
      - name: Docker logs
        uses: jwalton/gh-docker-logs@v1
